# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jH4lhE9F5y7bLeIIqpGyg2qqVsxFrgjU
"""

from flask import Flask, request, jsonify
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import math
import AMD_Tools4 as amd  # AMD_Tools4.py が同じディレクトリにある前提

app = Flask(__name__)

@app.route("/get_temp", methods=["POST"])
def get_climate_data():
    d = request.get_json()
    lat, lon = map(float, (d["lat"], d["lon"]))
    threshold = float(d["threshold"])
    gdd1_target = float(d["gdd1"])
    ct1_start = datetime.fromisoformat(d["ct1_start"]).date()  
    ct1_end   = datetime.fromisoformat(d["ct1_end"]).date()
    
    threshold2 = float(d["threshold2"])
    gdd2_target = float(d["gdd2"])
    ct2_start = datetime.fromisoformat(d["ct2_start"]).date()  
    ct2_end   = datetime.fromisoformat(d["ct2_end"]).date()
    
    # 元コードにあった hosei は辞書から取得できない場合のエラー回避用
    hosei = float(d.get("hosei", 0.0))

    today = datetime.utcnow().date()
    
    # ==================================================================
    # 1. 基準年の設定（平年値と実測値の分離）
    # ==================================================================
    # 平年値のための基準年（常に現在の現実の年 - 3）
    current_year = today.year if today.month >= 4 else today.year - 1
    start_year_for_avg = current_year - 3

    # 実測データ・シミュレーションのための年（スプレッドシートの年）
    target_year = ct1_start.year if ct1_start.month >= 4 else ct1_start.year - 1

    # --- 平年値の計算（常に現在から過去3年） ---
    all_years_data = []
    for year in range(start_year_for_avg, start_year_for_avg + 3):
        start = f"{year}-04-01"
        end = f"{year+1}-03-31"
        try:
            temp, tim, *_ = amd.GetMetData("TMP_mea", [start, end], [lat, lat, lon, lon])
            flat_temp = temp[:, 0, 0]

            df = pd.DataFrame({
                "datetime": pd.to_datetime(tim),
                "tave": flat_temp
            })
            df["month_day"] = df["datetime"].dt.strftime("%m-%d")
            all_years_data.append(df[["month_day", "tave"]])
        except Exception:
            pass # データ取得エラー時の保護

    if all_years_data:
        df_concat = pd.concat(all_years_data)
        df_avg = df_concat.groupby("month_day", as_index=False)["tave"].mean()
        df_avg.rename(columns={"tave": "tave_avg"}, inplace=True)

        # 並び替え（4月始まり）
        def reorder_from_april(df):
            df = df.copy()
            df["sort_key"] = pd.to_datetime("2000-" + df["month_day"])
            df = df.sort_values("sort_key").reset_index(drop=True)
            start_idx = df[df["month_day"] == "04-01"].index[0]
            return pd.concat([df.iloc[start_idx:], df.iloc[:start_idx]]).drop(columns=["sort_key"]).reset_index(drop=True)

        df_avg = reorder_from_april(df_avg)
        df_avg["tave_avg"] = df_avg["tave_avg"].round(1)
    else:
        df_avg = pd.DataFrame(columns=["month_day", "tave_avg"])

    # --- 対象年度の実測値（＋タグ） ---
    # target_year（スプレッドシートの年）に連動して気象データを取得
    start_this = f"{target_year}-04-01"
    end_this = f"{target_year + 1}-03-31"
    
    try:
        temp_this, tim_this, *_ = amd.GetMetData("TMP_mea", [start_this, end_this], [lat, lat, lon, lon])
        prcp_this, *_ = amd.GetMetData("APCPRA",  [start_this, end_this], [lat, lat, lon, lon])
        df_this = pd.DataFrame({
            "date"      : pd.to_datetime(tim_this).map(lambda d: d.date()),
            "tave_this" : temp_this[:, 0, 0],
            "prcp_this" : prcp_this[:, 0, 0]       
        })    
    except Exception:
        df_this = pd.DataFrame(columns=["date", "tave_this", "prcp_this"])

    yesterday = today - timedelta(days=1)
    forecast_end = today + timedelta(days=26)

    def assign_tag(d):
        if d <= yesterday:
            return "past"
        elif d <= forecast_end:
            return "forecast"
        else:
            return "normal"
            
    if not df_this.empty:
        df_this["tag"] = df_this["date"].map(assign_tag)
        df_forecast = df_this.loc[df_this["tag"] == "forecast"].reset_index(drop=True)
    else:
        df_forecast = pd.DataFrame()

    # =========================================================
    # 📌 ヘルパー関数：任意期間の累積 GDD / 降水
    # =========================================================
    def make_hist_dict(date_start, date_end, thr, df_src):
        if date_end < date_start or df_src.empty:
            return {"date": None, "cum_ct": None, "cum_pr": None}
    
        mask = (df_src["date"] >= date_start) & (df_src["date"] <= date_end)
        if not mask.any():
            return {"date": None, "cum_ct": None, "cum_pr": None}
    
        tmp = df_src.loc[mask].copy()
        tmp["daily_ct"] = (tmp["tave_this"] - thr).clip(lower=0)
        return {
            "date"   : date_end.isoformat(),
            "cum_ct" : round(tmp["daily_ct"].sum(), 1),
            "cum_pr" : round(tmp["prcp_this"].sum(), 1)
        }

    if not df_forecast.empty:
        df_forecast["date"] = df_forecast["date"].map(lambda d: d.isoformat())

    if not df_this.empty and not df_avg.empty:
        df_this["month_day"] = df_this["date"].map(lambda d: d.strftime("%m-%d"))
        df_this = df_this.merge(df_avg[["month_day", "tave_avg"]], on="month_day", how="left")
        mask = df_this["tag"] == "normal"
        df_this.loc[mask, "tave_this"] = df_this.loc[mask, "tave_avg"]
        df_this.drop(columns=["month_day", "tave_avg"], inplace=True)

    # =========================================================
    # --- 積算範囲1 (CT1) ---
    # =========================================================
    if not df_this.empty:
        mask1 = (df_this["date"] >= ct1_start) & (df_this["date"] <= ct1_end)
        df_ct1_period = df_this.loc[mask1].reset_index(drop=True)
    else:
        df_ct1_period = pd.DataFrame()

    df_ct1 = df_ct1_period.copy()
    row_close1 = None # あとでct2の計算に使うための変数
    
    # 安全対策：データが空（0件）だった場合のエラー回避
    if df_ct1.empty:
        closest_dict = {}
    else:
        df_ct1["daily_ct"] = (df_ct1["tave_this"] - threshold).clip(lower=0).round(1)
        df_ct1["cum_ct"] = df_ct1["daily_ct"].cumsum().round(1)
        df_ct1["daily_pr"] = df_ct1["prcp_this"].round(1)
        df_ct1["cum_pr"] = df_ct1["daily_pr"].cumsum().round(1)

        df_ct1["abs_diff"] = (df_ct1["cum_ct"] - gdd1_target).abs()
        idx_closest = df_ct1["abs_diff"].idxmin()
        row_close1   = df_ct1.loc[idx_closest]

        closest_dict = {
            "date"      : row_close1["date"].isoformat(),
            "cum_ct"    : round(row_close1["cum_ct"], 1),
            "daily_ct"  : round(row_close1["daily_ct"], 1),
            "abs_diff"  : round(row_close1["abs_diff"], 1)
        }

    # =========================================================
    # --- 積算範囲2 (CT2) ---
    # =========================================================
    if not df_this.empty:
        mask2 = (df_this["date"] >= ct2_start) & (df_this["date"] <= ct2_end)
        df_ct2_period = df_this.loc[mask2].reset_index(drop=True)
    else:
        df_ct2_period = pd.DataFrame()

    df_ct2 = df_ct2_period.copy()
    
    # 安全対策：データが空（0件）だった場合のエラー回避
    if df_ct2.empty:
        closest2_dict = {}
    else:
        df_ct2["daily_ct"] = (df_ct2["tave_this"] - threshold2).clip(lower=0).round(1)
        df_ct2["cum_ct"] = df_ct2["daily_ct"].cumsum().round(1)
        df_ct2["daily_pr"] = df_ct2["prcp_this"].round(1)
        df_ct2["cum_pr"] = df_ct2["daily_pr"].cumsum().round(1)

        df_ct2["abs_diff"] = (df_ct2["cum_ct"] - gdd2_target).abs()
        idx_closest2 = df_ct2["abs_diff"].idxmin()
        row_close2   = df_ct2.loc[idx_closest2]

        closest2_dict = {
            "date"      : row_close2["date"].isoformat(),
            "cum_ct"    : round(row_close2["cum_ct"], 1),
            "daily_ct"  : round(row_close2["daily_ct"], 1),
            "abs_diff"  : round(row_close2["abs_diff"], 1)
        }

    # =========================================================
    # ★ 昨日までの累積計算
    # =========================================================
    hist_dict1 = make_hist_dict(ct1_start, yesterday, threshold, df_this)
    
    # もしct1のデータが存在せず達成日(row_close1)が取得できていない場合は空にする
    if row_close1 is not None and not pd.isna(row_close1.get("date")):
        closest1_date = row_close1["date"]
        hist_dict2    = make_hist_dict(closest1_date, yesterday, threshold2, df_this)
    else:
        hist_dict2    = {"date": None, "cum_ct": None, "cum_pr": None}

    # NaN → None 対応
    def replace_nan_with_none(data):
        if isinstance(data, list):
            return [replace_nan_with_none(x) for x in data]
        elif isinstance(data, dict):
            return {k: replace_nan_with_none(v) for k, v in data.items()}
        elif isinstance(data, float) and math.isnan(data):
            return None
        else:
            return data
            
    # ここで date 列を文字列へ統一
    if not df_this.empty:
        df_this["date"] = df_this["date"].map(lambda d: d.isoformat())   
    if not df_ct1_period.empty:
        df_ct1_period["date"] = df_ct1_period["date"].map(lambda d: d.isoformat()) 
    if not df_ct2_period.empty:
        df_ct2_period["date"] = df_ct2_period["date"].map(lambda d: d.isoformat()) 
    if not df_ct1.empty:
        df_ct1["date"] = df_ct1["date"].map(lambda d: d.isoformat()) 
    if not df_ct2.empty:
        df_ct2["date"] = df_ct2["date"].map(lambda d: d.isoformat()) 
    
    df_avg_clean = replace_nan_with_none(df_avg.to_dict(orient="records"))
    df_this_clean = replace_nan_with_none(df_this.to_dict(orient="records"))
    df_ct1_period_clean = replace_nan_with_none(df_ct1_period.to_dict(orient="records"))
    df_ct2_period_clean = replace_nan_with_none(df_ct2_period.to_dict(orient="records"))
    df_ct1_clean = replace_nan_with_none(df_ct1.to_dict(orient="records"))
    df_ct2_clean = replace_nan_with_none(df_ct2.to_dict(orient="records"))
    df_forecast_clean = replace_nan_with_none(df_forecast.to_dict(orient="records"))

    return jsonify({
        "average": df_avg_clean,
        "this_year": df_this_clean,
        "ct1_period": df_ct1_period_clean,
        "ct1"       : df_ct1_clean,
        "gdd1_target": closest_dict,
        "ct2_period": df_ct2_period_clean,
        "ct2"       : df_ct2_clean,
        "gdd2_target": closest2_dict,
        "ct1_until_yesterday": hist_dict1, 
        "ct2_until_yesterday": hist_dict2, 
        "forecast": df_forecast_clean
    })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
